<Project>
  <PropertyGroup>
    <Authors>Harry Cordewener</Authors>
    <Company>Harry Cordewener</Company>
    <Copyright>Copyright © Harry Cordewener 2025</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/HarryCordewener/loradb-client</PackageProjectUrl>
    <RepositoryUrl>https://github.com/HarryCordewener/loradb-client</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageTags>loradb;graph;database;cypher;embedded</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
  </PropertyGroup>
</Project>
